'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
let db=null,session=null,companyId='',membershipRole='',access=null;
const cfg={supabaseUrl:'https://yqgovlrxyizobsnqycko.supabase.co',supabasePublishableKey:'sb_publishable_w3NPUZg6sWB4u64imbKxpg_f7UM_JTz'};
const roleLabel=r=>({owner:'Owner',admin:'Admin',foreman:'Foreman',worker:'Worker'}[r]||'Worker');
const initials=v=>String(v||'TM').split(/[@._\-\s]+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'TM';
function message(text,type='info'){const el=$('teamMessage');el.textContent=text;el.classList.remove('hidden');el.dataset.type=type;}
function clearMessage(){$('teamMessage').classList.add('hidden');}
async function authHeaders(){const {data}=await db.auth.getSession();session=data.session;if(!session)throw new Error('Please sign in to ScopeGuard first.');return {'Authorization':`Bearer ${session.access_token}`,'Content-Type':'application/json','x-scopeguard-company-id':companyId};}
async function api(path,options={}){const headers=await authHeaders();const r=await fetch(path,{...options,headers:{...headers,...options.headers}});const body=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(body.error||'Request failed.'),{status:r.status});return body;}
async function findCompany(){const {data,error}=await db.from('company_members').select('company_id,role').eq('user_id',session.user.id).limit(1);if(error)throw error;if(!data?.length)throw new Error('No ScopeGuard company was found for this account.');companyId=data[0].company_id;membershipRole=data[0].role||'';}
function roleOptions(member){if(member.role==='owner')return '<span class="pill">Owner</span>';return `<select class="team-role" aria-label="Change team member role" data-user="${esc(member.user_id)}"><option value="worker" ${member.role==='worker'?'selected':''}>Worker</option><option value="foreman" ${member.role==='foreman'?'selected':''}>Foreman</option><option value="admin" ${member.role==='admin'?'selected':''}>Admin</option></select>`;}
function memberRow(m){const active=m.status==='active';return `<div class="invoice-row team-member-row"><div style="display:flex;align-items:center;gap:12px"><span class="avatar" aria-hidden="true">${esc(initials(m.email||m.user_id))}</span><div><strong>${m.role==='owner'?'Company owner':roleLabel(m.role)}</strong><p class="muted">${esc(m.email||m.user_id)}</p><span class="pill">${active?'Active':'Disabled'}</span></div></div><div>${roleOptions(m)} ${m.role!=='owner'?`<button class="ghost small disable-worker" data-user="${esc(m.user_id)}" ${active?'':'disabled'}>${active?'Disable':'Disabled'}</button>`:''}</div></div>`;}
function render(data){const team=data.team||[],pending=data.pendingInvitations||[];$('teamCount').textContent=String(team.filter(x=>x.status==='active').length);$('inviteCount').textContent=String(pending.length);$('teamList').innerHTML=team.length?team.map(memberRow).join(''):'<div class="empty-state"><strong>No team members yet</strong><p class="muted">Invite your first worker above to start building your crew.</p></div>';$('pendingList').innerHTML=pending.length?pending.map(i=>`<div class="invoice-row"><div style="display:flex;align-items:center;gap:12px"><span class="avatar" aria-hidden="true">${esc(initials(i.email))}</span><div><strong>${esc(i.email)}</strong><p class="muted">${esc(roleLabel(i.role))} · expires ${new Date(i.expires_at).toLocaleDateString()}</p></div></div><button class="ghost small revoke-invite" data-id="${esc(i.id)}">Revoke</button></div>`).join(''):'<div class="empty-state"><strong>No pending invitations</strong><p class="muted">New invitations will appear here until they are accepted or expire.</p></div>';document.querySelectorAll('.team-role').forEach(el=>el.onchange=()=>changeRole(el.dataset.user,el.value));document.querySelectorAll('.disable-worker').forEach(el=>el.onclick=()=>disableWorker(el.dataset.user));document.querySelectorAll('.revoke-invite').forEach(el=>el.onclick=()=>revokeInvite(el.dataset.id));}
async function load(){clearMessage();const sub=await api(`/api/subscription-status?companyId=${encodeURIComponent(companyId)}`);access=sub.access;membershipRole=sub.membership?.role||membershipRole;$('teamPlanBadge').textContent=sub.plan?.name||'ScopeGuard';if(!access?.entitlements?.team){$('inviteCard').classList.add('hidden');message('Team & Workers is included with ScopeGuard Business. Upgrade to invite and manage your crew.','upgrade');$('teamList').innerHTML='<div class="empty-state"><strong>Business feature</strong><p class="muted">Upgrade to Business to manage workers and roles.</p></div>';$('pendingList').innerHTML='<p class="muted">No invitations available on this plan.</p>';return;}if(!['owner','admin'].includes(membershipRole)){$('inviteCard').classList.add('hidden');message('You can view company access, but only the owner or an admin can manage workers.','permission');}const data=await api(`/api/team?companyId=${encodeURIComponent(companyId)}`);render(data);if(!['owner','admin'].includes(membershipRole)){document.querySelectorAll('.team-role,.disable-worker,.revoke-invite').forEach(el=>el.disabled=true);}}
async function invite(){const email=$('inviteEmail').value.trim(),role=$('inviteRole').value;if(!email)return message('Enter the worker email address.','error');$('inviteBtn').disabled=true;$('inviteBtn').textContent='Sending…';try{const result=await api('/api/team',{method:'POST',body:JSON.stringify({companyId,action:'invite',email,role})});$('inviteEmail').value='';message(`Invitation created for ${result.invitation.email}.`,'success');await load();}catch(e){message(e.message,'error');}finally{$('inviteBtn').disabled=false;$('inviteBtn').textContent='Send invitation';}}
async function changeRole(userId,role){try{await api('/api/team',{method:'POST',body:JSON.stringify({companyId,action:'role',userId,role})});message(`Team member updated to ${roleLabel(role)}.`,'success');await load();}catch(e){message(e.message,'error');await load();}}
async function disableWorker(userId){if(!confirm('Disable this worker’s ScopeGuard access?'))return;try{await api('/api/team',{method:'POST',body:JSON.stringify({companyId,action:'disable',userId})});message('Worker access disabled.','success');await load();}catch(e){message(e.message,'error');}}
async function revokeInvite(invitationId){if(!confirm('Revoke this invitation?'))return;try{await api('/api/team',{method:'POST',body:JSON.stringify({companyId,action:'revoke-invite',invitationId})});message('Invitation revoked.','success');await load();}catch(e){message(e.message,'error');}}
$('inviteBtn').onclick=invite;$('backBtn').onclick=()=>location.href='/';$('teamHomeNav').onclick=()=>location.href='/';$('inviteEmail').addEventListener('keydown',e=>{if(e.key==='Enter')invite();});
(async()=>{try{db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);const {data}=await db.auth.getSession();session=data.session;if(!session){location.href='/';return;}await findCompany();await load();}catch(e){message(e.message,'error');$('inviteCard').classList.add('hidden');}})();
