const crypto = require('crypto');

function need(name){ const v=process.env[name]; if(!v) throw new Error(`${name} is not configured.`); return v; }
function b64url(v){ return Buffer.from(v).toString('base64url'); }
function signState(payload){ const secret=need('OAUTH_STATE_SECRET'); const body=b64url(JSON.stringify(payload)); const sig=crypto.createHmac('sha256',secret).update(body).digest('base64url'); return `${body}.${sig}`; }
function verifyState(state){ const secret=need('OAUTH_STATE_SECRET'); const [body,sig]=String(state||'').split('.'); if(!body||!sig) throw new Error('Invalid OAuth state.'); const expected=crypto.createHmac('sha256',secret).update(body).digest('base64url'); if(!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected))) throw new Error('Invalid OAuth state.'); const p=JSON.parse(Buffer.from(body,'base64url').toString()); if(!p.exp||Date.now()>p.exp) throw new Error('OAuth session expired.'); return p; }
function key(){ return crypto.createHash('sha256').update(need('EMAIL_TOKEN_ENCRYPTION_KEY')).digest(); }
function encrypt(text){ const iv=crypto.randomBytes(12); const cipher=crypto.createCipheriv('aes-256-gcm',key(),iv); const enc=Buffer.concat([cipher.update(String(text),'utf8'),cipher.final()]); return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${enc.toString('base64url')}`; }
function decrypt(blob){ const [iv,tag,data]=String(blob||'').split('.'); const d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64url')); d.setAuthTag(Buffer.from(tag,'base64url')); return Buffer.concat([d.update(Buffer.from(data,'base64url')),d.final()]).toString(); }
async function userFromBearer(req){ const auth=req.headers.authorization||''; if(!auth.startsWith('Bearer ')) throw Object.assign(new Error('Sign in first.'),{status:401}); const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL||'https://yqgovlrxyizobsnqycko.supabase.co'; const apikey=process.env.SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_w3NPUZg6sWB4u64imbKxpg_f7UM_JTz'; const r=await fetch(`${url}/auth/v1/user`,{headers:{Authorization:auth,apikey}}); if(!r.ok) throw Object.assign(new Error('Your session expired. Sign in again.'),{status:401}); return r.json(); }
function serviceHeaders(){ return {'apikey':need('SUPABASE_SERVICE_ROLE_KEY'),'Authorization':`Bearer ${need('SUPABASE_SERVICE_ROLE_KEY')}`,'Content-Type':'application/json'}; }
function supabaseUrl(){ return process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL||'https://yqgovlrxyizobsnqycko.supabase.co'; }
async function getConnection(userId){ const r=await fetch(`${supabaseUrl()}/rest/v1/email_connections?user_id=eq.${encodeURIComponent(userId)}&provider=eq.google&select=*`,{headers:serviceHeaders()}); if(!r.ok) throw new Error('Could not read email connection.'); return (await r.json())[0]||null; }
async function saveConnection(row){ const r=await fetch(`${supabaseUrl()}/rest/v1/email_connections?on_conflict=user_id,provider`,{method:'POST',headers:{...serviceHeaders(),'Prefer':'resolution=merge-duplicates,return=representation'},body:JSON.stringify(row)}); if(!r.ok) throw new Error(`Could not save email connection: ${await r.text()}`); return (await r.json())[0]; }
async function refreshAccess(refreshToken){ const body=new URLSearchParams({client_id:need('GOOGLE_CLIENT_ID'),client_secret:need('GOOGLE_CLIENT_SECRET'),refresh_token:refreshToken,grant_type:'refresh_token'}); const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body}); const j=await r.json(); if(!r.ok) throw new Error(j.error_description||'Google authorization expired. Reconnect Gmail.'); return j.access_token; }
module.exports={need,signState,verifyState,encrypt,decrypt,userFromBearer,getConnection,saveConnection,refreshAccess,serviceHeaders,supabaseUrl};
